### ISSUE TITLE
Error al editar una categoria

### ISSUE THREAD

**Issue by emiarias** [Gonzalomorales1001/Surveyjob-frontend#27]
**Proceso**
Luego de ingresar como administrador, al intentar editar una categoria

**Resultado esperado**
Editar la categoria que se visualiza en la tabla.

**Resultado actual**
Siempre muestra el mensaje de error al editar categoria, la sesion a expirado aún cuando recien se loguea el administrador.

**Captura**
![image](https://github.com/Gonzalomorales1001/Surveyjob-frontend/assets/18445151/56c79f70-494b-4baf-8b77-2db338917688)

**Comment by Gonzalomorales1001** [comment]
El error al parecer era de Netlify, ya que el proyecto desplegado en desarrollo (localhost:5173) funcionaba correctamente. Ya ha sido actualizado
