### ISSUE TITLE
Validar los campos al crear una encuesta

### ISSUE THREAD

**Issue by emiarias** [Gonzalomorales1001/Surveyjob-frontend#30]
**Proceso**
Al crear una encuesta

**Resultado esperado**
El campo del título de la encuesta deja ingresar demasiados caracteres

**Resultado actual**
Al crear la encuesta en la tabla de la página del administrador el titulo excede el espacio disponible.

**Captura**
![image](https://github.com/Gonzalomorales1001/Surveyjob-frontend/assets/18445151/0bc70712-40bd-44fd-8988-43c2bfcb6626)

**Comment by Gonzalomorales1001** [comment]
Se ha agregado validaciones a la hora de crear una encuesta. En caso de ser vulneradas, el servidor ahora cuenta con una limitación a la hora de postear encuestas con títulos muy grandes. Aun así, se agregaron clases de CSS al texto para que no sobresalga de la sección de administración de encuestas
